name = "t07-plandoc-diary-2"
main = "src/index.js"
compatibility_date = "2024-09-23"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "t07-plandoc-diary-2-db"
database_id = "REPLACE_WITH_YOUR_DATABASE_ID"
